export const MajorData = [
    "Teknik Informatika",
    "Sistem Informasi",
    "Teknik Elektro",
    "Teknik Mesin",
    "Teknik Sipil",
    "Teknik Kimia",
    "Teknik Industri",
    "Teknik Lingkungan",
    "Teknik Arsitektur",
    "Teknik Geologi",
    "Teknik Geofisika",
    "Teknik Perkapalan",
    "Teknik Pertambangan",
    "Teknik Perminyakan",
    "Teknik Metalurgi",
    "Teknik Material",
    "Teknik Telekomunikasi",
    "Teknik Nuklir",
    "Teknik Fisika",
    "Teknik Biomedis",
    "Teknologi Pangan",
    "Teknologi Hasil Pertanian",
    "Teknologi Informasi",
    "Ilmu Komputer",
    "Matematika",
    "Fisika",
    "Kimia",
    "Biologi",
    "Statistika",
    "Farmasi",
    "Kedokteran",
    "Kedokteran Gigi",
    "Kedokteran Hewan",
    "Ilmu Keperawatan",
    "Ilmu Kesehatan Masyarakat",
    "Ilmu Gizi",
    "Psikologi",
    "Hukum",
    "Ekonomi",
    "Akuntansi",
    "Manajemen",
    "Administrasi Bisnis",
    "Administrasi Publik",
    "Hubungan Internasional",
    "Ilmu Komunikasi",
    "Sosiologi",
    "Antropologi",
    "Ilmu Politik",
    "Pendidikan Guru Sekolah Dasar",
    "Pendidikan Anak Usia Dini"
  ];
  