export const UniversityData = [
    "Universitas Indonesia",
    "Universitas Terbuka",
    "Universitas Gadjah Mada",
    "Universitas Diponegoro",
    "Universitas Hasanuddin",
    "Universitas Sebelas Maret",
    "Universitas Brawijaya",
    "Universitas Sam Ratulangi",
    "Universitas Pattimura",
    "Universitas Udayana",
    "Universitas Musamus",
    "Universitas Mataram",
    "Universitas Cendrawasih",
    "Universitas Tanjungpura",
    "Universitas Jenderal Soedirman",
    "Universitas Tadulako",
    "Universitas Negeri Malang",
    "Universitas Airlangga",
    "Universitas Negeri Yogyakarta",
    "Universitas Negeri Semarang",
    "Universitas Negeri Surabaya",
    "Universitas Negeri Jakarta",
    "Universitas Negeri Manado",
    "Universitas Negeri Makassar",
    "Universitas Negeri Ganesha",
    "Universitas Negeri Khairun",
    "Universitas Trunojoyo Madura",
    "Universitas Negeri Gorontalo",
    "Universitas Sulawesi Barat",
    "Universitas Sembilan Belas November Kolaka",
    "Universitas Pembangunan Nasional Veteran Jakarta",
    "Universitas Pembangunan Nasional Veteran Yogyakarta",
    "Universitas Pembangunan Nasional Veteran Jawa Timur",
    "Universitas Pertahanan Indonesia",
    "Universitas Timor",
    "Universitas Nusa Cendana",
    "Universitas Haluoleo",
    "Universitas Padjadjaran",
    "Universitas Pendidikan Indonesia",
    "Universitas Sumatra Utara",
    "Universitas Andalas",
    "Universitas Sriwijaya",
    "Universitas Syiah Kuala",
    "Universitas Riau",
    "Universitas Jambi",
    "Universitas Palangkaraya",
    "Universitas Jember",
    "Universitas Lampung",
    "Universitas Bengkulu",
    "Universitas Negeri Medan",
    "Universitas Negeri Padang",
    "Universitas Sultan Ageng Tirtayasa",
    "Universitas Malikussaleh",
    "Universitas Bangka Belitung",
    "Universitas Maritim Raja Ali Haji",
    "Universitas Samudra",
    "Universitas Tidar",
    "Universitas Siliwangi",
    "Universitas Teuku Umar",
    "Universitas Singaperbangsa Karawang",
    "Universitas Lambung Mangkurat",
    "Universitas Mulawarman",
    "Universitas Borneo Tarakan",
    "Institut Teknologi Bandung",
    "Institut Pertanian Bogor",
    "Institut Teknologi Sepuluh November",
    "Institut Seni Indonesia Padang Panjang",
    "Institut Seni Budaya Indonesia Bandung",
    "Institut Teknologi Sumatera",
    "Institut Seni Budaya Indonesia Aceh",
    "Institut Teknologi Kalimantan",
    "Institut Seni Indonesia Yogyakarta",
    "Institut Seni Indonesia Denpasar",
    "Institut Seni Indonesia Surakarta",
    "Institut Seni Budaya Indonesia Tanah Papua",
    "Institut Teknologi Bacharuddin Jusuf Habibie"
  ];
  